# print macro commands on screen
/control/verbose 0

###################################################################
# geometry must be specified before /run/initialize               # 
/geometry/source /pioneer/main/geometry/generator/gdml/test_output.gdml

# End of geometry configuration                                   # 
###################################################################

###################################################################
# Configuration of the physics to be used                         # 

/Physics/SelectList QGSP_BERT
/process/had/verbose 0
/process/em/verbose 0

# Add optical physics.
#/Physics/AddOptics
#/process/optical/verbose 1
#/process/optical/processActivation Cerenkov false
#/process/optical/processActivation Scintillation false
#/process/optical/processActivation OpAbsorption true
#/process/optical/processActivation OpRayleigh true
#/process/optical/processActivation OpMieHG true
#/process/optical/processActivation OpBoundary true
#/process/optical/processActivation OpWLS true
#/process/optical/processActivation OpWLS2 true
#
#/process/optical/scintillation/verbose 1
#/process/optical/scintillation/setByParticleType false
#/process/optical/scintillation/setTrackInfo true
#/process/optical/scintillation/setFiniteRiseTime false
#/process/optical/scintillation/setStackPhotons true
#/process/optical/scintillation/setTrackSecondariesFirst true

# Decay mode selection
#/decay/all
#/decay/pimunu
#/decay/rad_muon
#/decay/pienu
#/decay/pienug
#/decay/rad_michel
#/decay/rad_michel_rad_muon
#/decay/pi_dif_e
#/decay/pi_dif_michel
#/decay/mu_dif
#/decay/pibeta


# End of physics configuration                                    # 
###################################################################

###################################################################
# Configuration of the output to be written                       # 

# path to output file. "#RUN#" will be replaced by the run ID
/output/FileName ./pienu#RUN#

# Switching on/off branches in the output TTree
/output/SaveInit         true
/output/SaveTrack        false
/output/SaveCalo         true
/output/SaveAtar         true
/output/SaveSipm         true


# End of output configuration                                     # 
###################################################################


#==================================================================
# Initialise the run 
/run/initialize

# check physics processes and particles.
# Beware, output is somewhat messy in multithreaded mode
# /process/list
# /particle/list
# /geometry/list

# Configure pion beam
/gen/select beam

# Beam parameters
/gen/beam/momentum     65 MeV
/gen/beam/momsigma    1.4 MeV
/gen/beam/xmean         0 mm
/gen/beam/ymean         0 mm
/gen/beam/xsigma       10 mm
/gen/beam/ysigma       10 mm
/gen/beam/zpos      -1200 mm

# Beam contaminations (0 - 1.00)
/gen/beam/muons         0
/gen/beam/positrons     0

# configure the generic particle source
#/gps/particle pi+
#/gps/energy 0.0 MeV
#/gps/pos/type Volume
#/gps/pos/shape Para
#/gps/pos/centre 0 0 0 mm
#/gps/pos/halfx 10 mm
#/gps/pos/halfy 10 mm
#/gps/pos/halfz 3 mm

# =================================================================

# visualize geometry and events for debugging
#/vis/open HepRepFile
#/vis/drawVolume
#/vis/scene/add/trajectories

# dump a few events on screen for debugging
#/random/setSeeds 
#/tracking/verbose 0


# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# Start the run

/run/beamOn 1
